helpers:
  aws:
    s3BucketName: sardalprojects
    s3FilePath: 0015dea2-f5e3-4de3-aa50-8910d9e8f015.wav
    s3ExpirationInSeconds: 1800
  google:
    bucketName: sardalprojects
    uploadFileName: 0015dea2-f5e3-4de3-aa50-8910d9e8f015.wav
    initiateResumableUploadBaseUrl: https://www.googleapis.com/upload/storage/v1/
